services:
  # --- 1. MINECRAFT SERVER ---
  mc-server:
    image: itzg/minecraft-bedrock-server:latest
    container_name: mc-server
    restart: unless-stopped
    network_mode: "host"
    environment:
      EULA: "TRUE"
    volumes:
      - ./minecraft-data:/data
    stdin_open: true
    tty: true